# Directories
source: .
destination: _site
layouts_dir: _layouts
includes_dir: _includes

# Site title and description
title:              hipsteranimals
description:        hipsteranimals official website
lang:               en

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title

# Site base hostname & protocol, e.g. http://example.com
url:                "http://hipsteranimals.com"

# Build settings
markdown:           kramdown
highlighter:        rouge

plugins:
  - jekyll-feed
exclude:
  - '**/Gemfile'
  - '**/Gemfile.lock'
  - '**/node_modules'
  - '**/package.json'

collections:
  theme:
    output: true

# Defaults
defaults:
  - values:
      layout: "default"
      twitter: "https://twitter.com/punksykick"
      footnote: "cry me a hipster"
      menu:
        - title: "Our Story"
          name: "our-story"
        - title: "About"
          name: "about"